# Generated by Django 4.1.5 on 2023-01-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-01-10'),
            preserve_default=False,
        ),
    ]
